#!/usr/bin/env bash

CONFIG_PATH="$HOME/.kube/config"
TEMP_CONFIG_PATH="$HOME/.kube/config_temp"

if [ "$#" -eq 0 ]; then
    echo "Usage: $0 <kubectl arguments>"
    exit 1
fi

awk '{gsub(/C:[^ ]*tsh\.exe/, "tsh"); print}' "$CONFIG_PATH" > "$TEMP_CONFIG_PATH"

export KUBECONFIG="$TEMP_CONFIG_PATH"
echo -e "Cluster: \e[32m$(kubectl config current-context)\e[0m"

kubectl "$@"
